# Generated by Django 2.1.4 on 2019-02-28 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('initial_cash', models.FloatField(default=0)),
                ('cash', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('stock_exchange', models.CharField(blank=True, max_length=150)),
                ('market_cap', models.FloatField(default=0, null=True)),
                ('last_price', models.FloatField(default=0, null=True)),
                ('price_sales_ratio', models.FloatField(default=0, null=True)),
                ('dividend_yield', models.FloatField(default=0, null=True)),
                ('volatility', models.FloatField(null=True)),
                ('value_score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock'),
        ),
        migrations.AddField(
            model_name='operation',
            name='portfolio_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.PortfolioStock'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliostock',
            unique_together={('portfolio', 'stock')},
        ),
    ]
